# Default values for time-tracker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.howto.solutions/artem/time-tracker
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hostname: time-tracker.howto.solutions
